services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - pg
    environment:
      APP_CONFIG__DB__URL: postgres://user:password@pg:5432/app
    env_file:
      - backend/app/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  pg:
    image: postgres
    container_name: postgres_db
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: app
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: